name: Android tests HUAWEI
on:
  push:
    branches:
      - develop-HUAWEI
jobs:
  test_on_emulator:
    name: Tests with emulator
    runs-on: privileged
    container:
      image: ghcr.io/bitfireat/docker-android-ci:main
      options: --privileged
      env:
        ANDROID_HOME: /sdk
        ANDROID_AVD_HOME: /root/.android/avd
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: gradle/wrapper-validation-action@v2

      - name: Cache gradle dependencies
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
      - name: Start emulator
        run: start-emulator.sh
      - name: Run connected tests
        run: ./gradlew app:connectedHuaweiDebugAndroidTest
      - name: Archive results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            app/build/reports
