name: Android tests HUAWEI
on:
  push:
    branches:
      - develop-HUAWEI
jobs:
  test_on_emulator:
    name: Tests with emulator
    runs-on: ubuntu-latest-4-cores
    strategy:
      matrix:
        api-level: [ 31 ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: gradle/wrapper-validation-action@v2

      - name: Cache gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew app:connectedHuaweiDebugAndroidTest

      - name: Archive results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            app/build/reports
