name: Build Test APK
on:
  pull_request:
  push:
    branches-ignore:
      - 'dependabot/**'
      - 'l10n_develop'

jobs:
  build:
    name: Build OSE Debug APK
    runs-on: ubuntu-latest
    if: github.actor != 'patrickunterwegs'
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
      - name: set up JDK 21
        uses: actions/setup-java@v6
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Build Debug APK
        run: ./gradlew assembleOseDebug

      - name: Upload APK
        uses: actions/upload-artifact@v7
        with:
          name: jtxboard-ose-debug-apk
          path: app/build/outputs/apk/ose/debug/*.apk
