# template: https://levelup.gitconnected.com/baseline-profiles-github-actions-ce8bc6858bb3

# Workflow name
name: Generate Baseline-Profiles

# Workflow title
# run-name: ${{ github.actor }} requested a workflow

# Event trigger so this actions gets executed every time a push is made on the main branch
# Change this event to what suits your project best.
# Read more at https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  workflow_dispatch

# Environment variables (Optional)
# Small projects might have signingConfigs locally. This could lead to failures on GitHub Actions.
# If that's the case, upload your properties defined locally to GitHub Secrets.

# On your signingConfigs, you can recover GitHub Secrets using: variable = System.getenv("VARIABLE")

# Then uncomment this block properly defining your uploaded variables
# env:
#  VARIABLE: ${{ secrets.VARIABLE }}

# Read more at https://docs.github.com/en/actions/security-guides/encrypted-secrets

# Jobs to executed on GitHub machines
jobs:
  generate_baseline_profiles:
    name: Generate Baseline-Profiles
    runs-on: ubuntu-latest-4-cores
    strategy:
      matrix:
        api-level: [ 34 ]
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
      - uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v6

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Cache AVD and APKs
        uses: actions/cache@v6
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Prepare keystore
        run: echo ${{ secrets.android_keystore_base64 }} | base64 -d >$GITHUB_WORKSPACE/keystore.jks

      - name: Create baseline profiles
        uses: reactivecircus/android-emulator-runner@v2
        env:
          ANDROID_KEYSTORE: ${{ github.workspace }}/keystore.jks
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.android_keystore_password }}
          ANDROID_KEY_ALIAS: ${{ secrets.android_key_alias }}
          ANDROID_KEY_PASSWORD: ${{ secrets.android_key_password }}
          CROWDIN_API_KEY: ${{ secrets.crowdin_api_key }}
          GOOGLE_GEO_API_KEY: ${{ secrets.google_geo_api_key }}
          GH_CONTRIBUTORS_API_KEY: ${{ secrets.gh_contributors_api_key }}
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew :app:generateOseReleaseBaselineProfile :app:generateGplayReleaseBaselineProfile :app:generateAmazonReleaseBaselineProfile
      
      # Commits the generated Baseline Profile to your origin/remote
      - name: Commit Baseline Profiles
        run: |
          git config --global user.name 'Baseline Profiles - GitHub Actions'
          git config --global user.email 'github@actions'
          git add app/src/main/baseline-prof.txt
          git commit -m "Generate baseline profiles"
          git push
