name: Unit tests
on: push
jobs:
  test:
    name: Tests without emulator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/wrapper-validation@v6

      - name: Run lint and unit tests
        run: ./gradlew app:lintOseDebug app:testGplayDebugUnitTest
      - name: Archive results
        uses: actions/upload-artifact@v7
        with:
          name: test-results2
          path: |
            app/build/outputs/lint*
            app/build/reports
