name: Unit tests
on: push
jobs:
  test:
    name: Tests without emulator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - uses: gradle/wrapper-validation-action@v3

      - name: Run lint and unit tests
        run: ./gradlew app:lintOseDebug app:testGplayDebugUnitTest
      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: test-results2
          path: |
            app/build/outputs/lint*
            app/build/reports
