name: Unit tests
on: push
jobs:
  test:
    name: Tests without emulator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - uses: gradle/actions/wrapper-validation@v3

      - name: Run lint and unit tests
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 30
          max_attempts: 3
          retry_wait_seconds: 5
          command: ./gradlew app:lintOseDebug app:testGplayDebugUnitTest
      - name: Archive results
        uses: actions/upload-artifact@v7
        with:
          name: test-results2
          path: |
            app/build/outputs/lint*
            app/build/reports
